# Trigger website deployment to rebuild docs whenever main branch has been changed
name: Deploy to website

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-24.04
    steps:
      - run: |
          curl -X POST -u ":${{ secrets.WEBSITE_PAT}}" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/clue/framework-x-website/actions/workflows/ci.yml/dispatches -d '{"ref":"main"}'
